DROP DATABASE IF EXISTS cluedo;
CREATE DATABASE cluedo;
USE cluedo;
CREATE TABLE PLAYER(
					ID VARCHAR(60),
					PASSWORD VARCHAR(60),
					WINNINGGAMES INT NOT NULL,
					FRIENDS VARCHAR(5000),
					GAMESPLAYED INT NOT NULL,
					PRIMARY KEY (ID)
					)ENGINE=InnoDB;
CREATE TABLE GAME(
					ACTIVEGAME VARCHAR(60),
					ID_P VARCHAR (60),
					DATE VARCHAR (60),
					DURATION INT NOT NULL,
					WINNER VARCHAR (60),
					FOREIGN KEY(ID_P) REFERENCES PLAYER (ID),
					PRIMARY KEY (ID_P)
					)ENGINE =InnoDB;  
CREATE TABLE PARTICIPATION(
					PLAYER VARCHAR(60),
					GAME VARCHAR(60),
					POSITION INT NOT NULL,
					FOREIGN KEY (PLAYER) REFERENCES PLAYER (ID),
					FOREIGN KEY (GAME) REFERENCES GAME (ID_P)
					)ENGINE = InnoDB;

INSERT INTO PLAYER VALUES('Ruth','copitos',3,'Alex',3);
INSERT INTO PLAYER VALUES('Alex','gatos',0,'Ruth/Pablo',3);
INSERT INTO PLAYER VALUES('Daniel','piedras',0,'Pablo',3);
INSERT INTO PLAYER VALUES('Pablo','perros',0,'Daniel',1);

INSERT INTO GAME VALUES('1','Ruth/Alex/Daniel','17/10/2020:17:10:26',20,'Ruth');
INSERT INTO GAME VALUES('2','Ruth/Alex/Daniel','17/10/2020:17:40:32',30,'Ruth');
INSERT INTO GAME VALUES('3','Ruth/Alex/Daniel','17/10/2020:19:12:54',23,'Ruth');
