DROP DATABASE IF EXISTS m3cluedo;
CREATE DATABASE m3cluedo;
USE m3cluedo;

CREATE TABLE PLAYER(
	ID VARCHAR(60),
	PASS VARCHAR(60),
	FRIENDS VARCHAR(5000),
	PRIMARY KEY (ID)
)ENGINE=InnoDB;

CREATE TABLE GAME(
	ID_P INT NOT NULL,
	DATE VARCHAR(60),
	DURATION INT NOT NULL,
	PRIMARY KEY(ID_P)
)ENGINE=InnoDB;

CREATE TABLE PARTICIPATION(
	PLAYER VARCHAR(60),
	GAME INT NOT NULL,
	POSITION INT NOT NULL,
	FOREIGN KEY (PLAYER) REFERENCES PLAYER(ID),
	FOREIGN KEY (GAME) REFERENCES GAME (ID_P)
)ENGINE=InnoDB;

INSERT INTO PLAYER VALUES('Alex','gatos','Ruth/Daniel/Miriam');
INSERT INTO PLAYER VALUES('Ruth','perros', 'Alex/Daniel/Miriam');
INSERT INTO PLAYER VALUES('Daniel','daniel','Ruth/Alex/Miriam');
INSERT INTO PLAYER VALUES('Miriam','rodriguez','Ruth/Daniel/Alex');

INSERT INTO GAME VALUES(1,'18/10/2020:09:50',20);
INSERT INTO GAME VALUES(2,'19/10/2020:09:50',30);
INSERT INTO GAME VALUES(3,'20/10/2020:09:50',40);

INSERT INTO PARTICIPATION VALUES('Alex','1',1);
INSERT INTO PARTICIPATION VALUES('Alex','2',1);
INSERT INTO PARTICIPATION VALUES('Alex','3',2);
INSERT INTO PARTICIPATION VALUES('Ruth','1',2);
INSERT INTO PARTICIPATION VALUES('Ruth','2',2);
INSERT INTO PARTICIPATION VALUES('Ruth','3',1);
INSERT INTO PARTICIPATION VALUES('Daniel','1',3);
INSERT INTO PARTICIPATION VALUES('Daniel','2',4);
INSERT INTO PARTICIPATION VALUES('Miriam','2',3);
INSERT INTO PARTICIPATION VALUES('Miriam','3',3);
